package expo.modules.prayerpanel

import android.Manifest
import android.app.AlarmManager
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build

/**
 * Posts the next-prayer panel and arms one alarm for its next change.
 *
 * The countdown is drawn by the system (a chronometer counting down to the next
 * prayer), so nothing runs between changes: no foreground service, no wake-ups
 * beyond one alarm at each prayer and one 30 minutes after it. The notification
 * is deliberately not ongoing — the user can swipe it away, and it comes back at
 * the next change unless they turn the panel off in the app.
 */
object PanelNotifier {
  const val CHANNEL_ID = "prayer_panel_v1"
  const val ACTION_UPDATE = "com.barakah.stories.prayerpanel.UPDATE"
  private const val NOTIFICATION_ID = 41007
  private const val REQUEST_ALARM = 41008
  private const val REQUEST_OPEN = 41009

  /** If the next change never arrives (an OEM killed the alarm), drop a stale panel this long after zero. */
  private const val STALE_AFTER_MS = 10 * 60_000L

  /** Shows what belongs on screen now and arms the alarm for the next change. */
  fun refresh(context: Context) {
    val now = System.currentTimeMillis()
    val entries = PanelStore.load(context)
    val current = entries.lastOrNull { it.at <= now }
    val upcoming = entries.firstOrNull { it.at > now }
    if (current == null || current.countdownTo <= now) cancelNotification(context) else post(context, current, now)
    if (upcoming != null) arm(context, upcoming.at) else disarm(context)
  }

  fun clear(context: Context) {
    disarm(context)
    cancelNotification(context)
    PanelStore.clear(context)
  }

  fun canScheduleExact(context: Context): Boolean {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.S) return true
    val alarms = context.getSystemService(AlarmManager::class.java) ?: return false
    return alarms.canScheduleExactAlarms()
  }

  private fun canNotify(context: Context): Boolean {
    val manager = context.getSystemService(NotificationManager::class.java) ?: return false
    if (!manager.areNotificationsEnabled()) return false
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
      return context.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS) == PackageManager.PERMISSION_GRANTED
    }
    return true
  }

  private fun ensureChannel(context: Context) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
    val manager = context.getSystemService(NotificationManager::class.java) ?: return
    // Low importance: listed in the shade without sound, vibration or a heads-up.
    val channel = NotificationChannel(CHANNEL_ID, PanelStore.channelName(context), NotificationManager.IMPORTANCE_LOW)
    channel.setSound(null, null)
    channel.enableVibration(false)
    channel.setShowBadge(false)
    manager.createNotificationChannel(channel)
  }

  private fun post(context: Context, entry: PanelEntry, now: Long) {
    if (!canNotify(context)) return
    ensureChannel(context)
    val manager = context.getSystemService(NotificationManager::class.java) ?: return

    @Suppress("DEPRECATION")
    val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      Notification.Builder(context, CHANNEL_ID).setTimeoutAfter(entry.countdownTo - now + STALE_AFTER_MS)
    } else {
      Notification.Builder(context).setPriority(Notification.PRIORITY_LOW)
    }
    builder
      .setSmallIcon(smallIcon(context))
      .setContentTitle(entry.title)
      .setContentText(entry.body)
      .setWhen(entry.countdownTo)
      .setShowWhen(true)
      .setUsesChronometer(true)
      .setChronometerCountDown(true)
      .setOnlyAlertOnce(true)
      .setOngoing(false)
      .setAutoCancel(false)
      .setCategory(Notification.CATEGORY_REMINDER)
      .setVisibility(Notification.VISIBILITY_PUBLIC)
    openAppIntent(context)?.let { builder.setContentIntent(it) }

    try {
      manager.notify(NOTIFICATION_ID, builder.build())
    } catch (e: SecurityException) {
      // Permission revoked between the check and the post: nothing to show.
    }
  }

  private fun cancelNotification(context: Context) {
    context.getSystemService(NotificationManager::class.java)?.cancel(NOTIFICATION_ID)
  }

  /** The tinted notification icon generated by expo-notifications, or the app icon. */
  private fun smallIcon(context: Context): Int {
    val generated = context.resources.getIdentifier("notification_icon", "drawable", context.packageName)
    return if (generated != 0) generated else context.applicationInfo.icon
  }

  private fun openAppIntent(context: Context): PendingIntent? {
    val launch = context.packageManager.getLaunchIntentForPackage(context.packageName) ?: return null
    launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_RESET_TASK_IF_NEEDED)
    return PendingIntent.getActivity(
      context, REQUEST_OPEN, launch, PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT
    )
  }

  private fun alarmIntent(context: Context, flags: Int): PendingIntent? {
    val intent = Intent(context, PanelReceiver::class.java).setAction(ACTION_UPDATE)
    return PendingIntent.getBroadcast(context, REQUEST_ALARM, intent, PendingIntent.FLAG_IMMUTABLE or flags)
  }

  private fun arm(context: Context, at: Long) {
    val alarms = context.getSystemService(AlarmManager::class.java) ?: return
    val pending = alarmIntent(context, PendingIntent.FLAG_UPDATE_CURRENT) ?: return
    try {
      if (canScheduleExact(context)) {
        alarms.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, at, pending)
      } else {
        // Without the user's exact-alarm grant the panel may change a few minutes late;
        // the countdown itself is still exact because the system draws it.
        alarms.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, at, pending)
      }
    } catch (e: SecurityException) {
      alarms.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, at, pending)
    }
  }

  private fun disarm(context: Context) {
    val pending = alarmIntent(context, PendingIntent.FLAG_NO_CREATE) ?: return
    context.getSystemService(AlarmManager::class.java)?.cancel(pending)
    pending.cancel()
  }
}
