#!/usr/bin/env node
/**
 * Builds the offline country → city picker data from GeoNames.
 *
 * Source: https://download.geonames.org/export/dump/ — cities15000.zip (every
 * city over 15,000 people), countryInfo.txt and admin1CodesASCII.txt. GeoNames
 * is CC BY 4.0, so the app credits it on the About screen; keep that credit.
 *
 * Usage:
 *   curl -O https://download.geonames.org/export/dump/cities15000.zip && unzip cities15000.zip
 *   curl -O https://download.geonames.org/export/dump/countryInfo.txt
 *   curl -O https://download.geonames.org/export/dump/admin1CodesASCII.txt
 *   node scripts/gen-cities.mjs <directory holding those three files>
 *
 * Output:
 *   packages/assets/geo/countries.json      [{ cc, name, n }] sorted by name
 *   packages/assets/geo/cities/<CC>.json    { z: [timeZones], c: [[name, lat, lng, zoneIndex, region]] }
 *                                           cities sorted by population, largest first
 *   apps/mobile/src/geo/cityLoaders.generated.ts   one lazy require per country
 *
 * Every GeoNames city carries an IANA time zone, which is what lets alerts and
 * the clock display follow the chosen city rather than the phone.
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const src = resolve(process.argv[2] ?? '.cache/geonames');
const root = resolve(import.meta.dirname, '..');
const outDir = join(root, 'packages/assets/geo');
const loadersFile = join(root, 'apps/mobile/src/geo/cityLoaders.generated.ts');

const rows = (file) =>
  readFileSync(join(src, file), 'utf8')
    .split('\n')
    .filter((line) => line && !line.startsWith('#'))
    .map((line) => line.split('\t'));

const countryNames = new Map(rows('countryInfo.txt').map((r) => [r[0], r[4]]));
const regionNames = new Map(rows('admin1CodesASCII.txt').map((r) => [r[0], r[1]]));

const round = (n) => Math.round(Number(n) * 1e4) / 1e4;

/** cc → [{ name, lat, lng, tz, region, pop }] */
const byCountry = new Map();
for (const r of rows('cities15000.txt')) {
  const [, name, , , lat, lng, , , cc, , admin1, , , , pop, , , tz] = r;
  if (!cc || !tz || !countryNames.has(cc)) continue;
  const region = regionNames.get(`${cc}.${admin1}`) ?? '';
  if (!byCountry.has(cc)) byCountry.set(cc, []);
  byCountry.get(cc).push({ name, lat: round(lat), lng: round(lng), tz, region, pop: Number(pop) || 0 });
}

rmSync(join(outDir, 'cities'), { recursive: true, force: true });
mkdirSync(join(outDir, 'cities'), { recursive: true });

const countries = [];
let bytes = 0;
for (const [cc, cities] of byCountry) {
  cities.sort((a, b) => b.pop - a.pop || a.name.localeCompare(b.name));
  const zones = [...new Set(cities.map((c) => c.tz))];
  const file = {
    z: zones,
    c: cities.map((c) => [c.name, c.lat, c.lng, zones.indexOf(c.tz), c.region === c.name ? '' : c.region]),
  };
  const json = JSON.stringify(file);
  bytes += json.length;
  writeFileSync(join(outDir, 'cities', `${cc}.json`), json);
  countries.push({ cc, name: countryNames.get(cc), n: cities.length });
}
countries.sort((a, b) => a.name.localeCompare(b.name));
writeFileSync(join(outDir, 'countries.json'), JSON.stringify(countries));

mkdirSync(join(root, 'apps/mobile/src/geo'), { recursive: true });
const loaders = countries
  .map(({ cc }) => `  ${cc}: () => require('../../../../packages/assets/geo/cities/${cc}.json'),`)
  .join('\n');
writeFileSync(
  loadersFile,
  `// GENERATED by scripts/gen-cities.mjs from GeoNames (CC BY 4.0). Do not edit by hand.
/* eslint-disable @typescript-eslint/no-require-imports */
import type { CountryCityFile } from '@barakah/core';

/** One lazy require per country: a country's cities are parsed only when it is opened. */
export const CITY_LOADERS: Record<string, () => CountryCityFile> = {
${loaders}
};
`,
);

const total = countries.reduce((s, c) => s + c.n, 0);
console.log(`${countries.length} countries, ${total} cities, ${(bytes / 1e6).toFixed(2)} MB of city data`);
